### ISSUE TITLE
The type io.dronefleet.mavlink.protocol.MavlinkPacket cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by sabarishbollapragada** [dronefleet/mavlink#1]
I have downloaded the jar file from the maven central. But when I try to follow your example code for sending a mavlink message I get this error. I see that the MavlinkPacket class is in the mavlink-protocol but is that included in the jar file from maven?

**Comment by benbarkay** [comment]
You are right, the mavlink-protocol jar is not included. I'll correct this
in a day or two.

For now I suppose you could clone and build these jars so that you may
proceed with development/testing.

Sorry for that.
