### ISSUE TITLE
Serialization unit tests fail (Mac High Sierra and Java 1.8)

### ISSUE THREAD

**Issue by joelkoz** [dronefleet/mavlink#13]
I have been having problems with the serialization system.  In an attempt to "start fresh", I did the following:

1. Downloaded 1.0.10 from the "Releases" tab here on the main project and unzipped
2. gradle init
3. gradle build
4. gradle test

I got the following error message:
io.dronefleet.mavlink.serialization.payload.reflection.ReflectionPayloadSerializationTest > test FAILED
    java.lang.AssertionError at ReflectionPayloadSerializationTest.java:26

1 test completed, 1 failed
:test FAILED

I am doing this on a Macbook Pro, Mac OS X High Sierra (64 bit) with Java JRE build 1.8.0_91-b14

I got the same error message when doing a "gradle test" on my Github checkout of 1.0.9. The pull request I submitted about a "null pointer exception" I am sure is related to this issue.

**Comment by benbarkay** [comment]
Sorry that it took so long, I've released 1.0.12 with a fix for this. Could you verify that this resolves it?
