### ISSUE TITLE
data method is null in EncapsulatedData message

### ISSUE THREAD

**Issue by SilvainIADYS** [dronefleet/mavlink#21]
Hi,
I try to get the data in the EncapsulatedData message but it's null.
With this line :
`encapsulatedData.data().length`
I get this error :
`java.lang.NullPointerException: Attempt to get length of null array`

Is it a issue or I'm noob ? ^^

**Comment by benbarkay** [comment]
Are you using a version earlier than `1.1.4`?

**Comment by SilvainIADYS** [comment]
Yes, Thanks a lot
