### ISSUE TITLE
Mavlink enum vs Java enum

### ISSUE THREAD

**Issue by lmar** [dronefleet/mavlink#3]
There is a problem that Mavlink enums are getting mapped to Java enums. When you try to parse a Mavlink message that contains a value that is not part of the enum XML specification then the parser just throws an exception in ReflectionPayloadDeserializer::enumValue. 

This is especially problematic with io.dronefleet.mavlink.common.MavMode as the values in MAV_MODE are basically just example values. In practice you can receive any OR-combination of MAV_MODE_FLAGS in a field of type MAV_MODE.

It is probably necessary to use integer constants instead (or maybe something like java.util.BitSet?).

**Comment by benbarkay** [comment]
If your XML definition declares the field as `enum="YOUR_ENUM" display="bitmask"` then the plugin will generate that field as an `EnumFlagSet<YourEnum>`

**Comment by lmar** [comment]
But MAV_MODE and MAV_MODE_FLAGS are defined in common.xml, so you're not really supposed to change that, right?

Also EnumFlagSet does not help with unknown values. For example MAV_AUTOPILOT values are defined from 1 to 19. When I receive an unknown value I would want to know whether the actual value is 20 or 25.

**Comment by benbarkay** [comment]
If you define MAV_MODE and MAV_MODE_FLAGS enum in your XML file then rather than being overridden, they will be extended. (Your enum entries will be added to `MavMode` and `MavModeFlags`).

In any case, perhaps `EnumFlagSet` should work off of a value field with an actual bitmask rather than storing a set of enum values. This way the value could be set or retrieved. Would that help?

**Comment by lmar** [comment]
Yes, that would probably work. 

But I still think that should be the default for all enum fields. You should always expect to receive some unknown values. And these are legal messages so the parser should not throw an exception.

**Comment by benbarkay** [comment]
Alright, so I suppose I'll change `EnumFlagSet` and plugin sometime this weekend. Feel free to propose a pull request if you have some working adjustment.

As for the exception, if it gets to that it's thrown then this means we have underlying code that is defective (such as the deserialization code for enum fields in this instance), I'd rather correct these instead -- without these exceptions it might be harder to find/debug these. This is a very early stage library that has been tested in a limited fashion, these instances will diminish rapidly with your use cases seeing as we're doing work on it to support your use cases.

In any case, would like to note that your adoption of dronefleet-mavlink is appreciated by me, and I'm sure whoever else is going to be using `dronefleet-mavlink` in the future. I'll try to support you as best as I can with the time that I have to invest :)

**Comment by benbarkay** [comment]
@lmar I see your point now. It sucks that there won't be a statically typed hint at which enum the value is referring to though.

**Comment by lmar** [comment]
Yeah, I know, that's unfortunate. Maybe you could generate code similar to this:

```
interface BitMask {
  int getValue();
  default boolean isSet(BitMask other) {
    return (getValue() & other.getValue()) != 0;
  }
}

class MavModeFlags implements BitMask {
  private int value;

  public static MavModeFlags MAV_MODE_FLAG_SAFETY_ARMED = new MavModeFlags(128);
  public static MavModeFlags MAV_MODE_FLAG_MANUAL_INPUT_ENABLED = new MavModeFlags(64);
  public static MavModeFlags MAV_MODE_FLAG_HIL_ENABLED = new MavModeFlags(32);

  public MavModeFlags(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public MavModeFlags set(BitMask other) {
    return new MavModeFlags(getValue() | other.getValue());
  }
}

class MavMode implements BitMask {
  private int value;

  public static MavMode MAV_MODE_PREFLIGHT = new MavMode(0);
  public static MavMode MAV_MODE_STABILIZE_DISARMED = new MavMode(80);
  public static MavMode MAV_MODE_STABILIZE_ARMED = new MavMode(208);

  public MavMode(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }

  public MavMode set(BitMask other) {
    return new MavMode(getValue() | other.getValue());
  }
}
```

Not great. But at least somewhat convenient to use.

**Comment by benbarkay** [comment]
@Imar I was thinking something along these lines as well. I was thinking though that perhaps we could keep the enums themselves the way that they are, and only change the value fields, something like so:
```java
interface EnumField<T extends Enum> {
    // Returns the raw value of this field
    int value();

    // Returns true if the value of this field is mappable to an entry of T, or false
    boolean mappable();

    // Attempts to map the value of the field to an entry of T, or throws
    T map();

    // Returns true if (value() & enum) == enum for each enum in enums, or false
    // (this converts the specified enum entries to their value)
    boolean enabled(Enum ... enums);
}
```

So some static typing remains, but you're free to break out of the constraints of the "idiomatics" created by the library if they fail you. Perhaps I could also add `int value()` to enums to ease with extracting it from annotations.

So in that case, you can still:
```java
switch (field.map()) {
    // IDE autocomplete
}
```

or
```java
if (field.enabled(MavModeFlags.MAV_FLAG_HIL_ENABLED)) {
    // ...
}
```

Does this seem like a good idea to you? Or do you find that there's something else that I'm overlooking?

**Comment by benbarkay** [comment]
@lmar hopefully what I've pushed works for you. Let me know if you find this lacking in any other way.
