### ISSUE TITLE
Sending/Receiving custom message help

### ISSUE THREAD

**Issue by softwarecorridor** [dronefleet/mavlink#34]
I am trying to write an android app to send custom mavlink1.0 messages to a java server using mostly the same code over UDP

I have a dialect.xml that I am using to test sending custom messages.
```
<?xml version='1.0'?>
<mavlink>
     <include>common.xml</include>
	 <messages>
          <message id="444" name="WAYPOINT_TESTER">
               <description>WAYPOINT_TESTER</description>
               <field type="int8_t" name="waypoint_id">id</field>
          </message>
	</messages>
</mavlink>

```
I can build the message just fine

`WaypointTester tester = WaypointTester.builder().waypointId(1).build();`

on the android side before it goes over the pipe I see the data
in byte[] = [-2, 1, 0, 0, 0, -68, 1, 77, 57]
in hex = FE01000000BC014D39

on the other side I can see that data is reaching just fine, but the mavlink connection never reports that message.

If I send messages from the dialects included in the box it works fine,

 ```
    Heartbeat msg = Heartbeat.builder()
                .type(MavType.MAV_TYPE_GCS)
                .autopilot(MavAutopilot.MAV_AUTOPILOT_GENERIC)
                .systemStatus(MavState.MAV_STATE_ACTIVE)
                .mavlinkVersion(1)
                .build();
```

in byte[] = [-2, 9, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 4, 1, -8, -86]
in hex = FE0900000000000000000600000401F8AA

server side

`Heartbeat{type=EnumValue{value=6, entry=MAV_TYPE_GCS}, autopilot=EnumValue{value=0, entry=MAV_AUTOPILOT_GENERIC}, baseMode=EnumValue{value=0, entry=null}, customMode=0, systemStatus=EnumValue{value=4, entry=MAV_STATE_ACTIVE}, mavlinkVersion=1}`

**--steps that I used to build everything--**
(I am using windows)
1. drop the dialect.xml file into definition-xml folder
2. gradle clean
3. gradle jar
4. cd to mavlink-protocol
5. gradle clean
6. gradle jar
7. link the two jar files to the projects

**code**
So far it is pretty basic, I have two threads that have access to the MavlinkConnection:

sending thread
`connection.send1(0, 0, msg);`

receiving thread
```
MavlinkMessage message;
while ((message = connection.next()) != null) {
    System.out.println(message.getPayload());
}
```
I am not sure what I am doing wrong

**Comment by benbarkay** [comment]
Did you add the dialect when you built the connection?
e.g.
```java
MavlinkConnection connection = MavlinkConnection.builder(in,out)
    .dialect(MavlinkDialects.YOUR_DIALECT) // this line
    .build();
```

**Comment by benbarkay** [comment]
Change
```java
   Heartbeat msg = Heartbeat.builder()
               .type(MavType.MAV_TYPE_GCS)
               .autopilot(MavAutopilot.MAV_AUTOPILOT_GENERIC) // this
               .systemStatus(MavState.MAV_STATE_ACTIVE)
               .mavlinkVersion(1)
               .build();
```

to 
```java
   Heartbeat msg = Heartbeat.builder()
               .type(MavType.MAV_TYPE_GCS)
               .autopilot(MavAutopilot.MAV_AUTOPILOT_ARDUPILOTMEGA) // this
               .systemStatus(MavState.MAV_STATE_ACTIVE)
               .mavlinkVersion(1)
               .build();
```

**Comment by softwarecorridor** [comment]
Ok I didn't realize the Heartbeat part. I updated my system send a heartbeat message first (and have it automatically reply with one).  Neither side is recognizing the WaypointTester message.

###### Test pattern
<details>
  Both sides have:

 ```
MavlinkConnection connection = MavlinkConnection.builder(mavInputStream, mavOutputStream)
                        .dialect(MavAutopilot.MAV_AUTOPILOT_ARDUPILOTMEGA, new DialectDialect() ).build();
```

System A sends
```
Heartbeat hb = Heartbeat.builder()
                .type(MavType.MAV_TYPE_GCS)
                .autopilot(MavAutopilot.MAV_AUTOPILOT_ARDUPILOTMEGA)
                .systemStatus(MavState.MAV_STATE_ACTIVE)
                .mavlinkVersion(1)
                .build();
```
System B receives;
`Heartbeat{type=EnumValue{value=6, entry=MAV_TYPE_GCS}, autopilot=EnumValue{value=3, entry=MAV_AUTOPILOT_ARDUPILOTMEGA}, baseMode=EnumValue{value=0, entry=null}, customMode=0, systemStatus=EnumValue{value=4, entry=MAV_STATE_ACTIVE}, mavlinkVersion=1}`

System B replies with:
```
Heartbeat hb = Heartbeat.builder()
                .type(MavType.MAV_TYPE_GCS)
                .autopilot(MavAutopilot.MAV_AUTOPILOT_ARDUPILOTMEGA)
                .systemStatus(MavState.MAV_STATE_ACTIVE)
                .mavlinkVersion(1)
                .build();
```

System A receives:
`Heartbeat{type=EnumValue{value=6, entry=MAV_TYPE_GCS}, autopilot=EnumValue{value=3, entry=MAV_AUTOPILOT_ARDUPILOTMEGA}, baseMode=EnumValue{value=0, entry=null}, customMode=0, systemStatus=EnumValue{value=4, entry=MAV_STATE_ACTIVE}, mavlinkVersion=1}`

System A sends:
` WaypointTester tester = WaypointTester.builder().waypointId(10).build();`

System B receives some data over the pipe but the Mavlink connection doesn't report anything
```
 byte: [-2, 1, 1, 0, 0, -68, 10, -50, -39]
 hex: FE01010000BC0ACED9
```
</details>

**Comment by YeganehNobakht** [comment]
Hi, I recently use dronefleet library to send mavlink2 message to a pixhawk with serial port. When I send CommandLong message, nothing happen in pixhawk.

        CommandLong rtlMessage = CommandLong.builder()
                .targetSystem(1)
                .targetComponent(1)
                .command(MavCmd.MAV_CMD_NAV_RETURN_TO_LAUNCH)
                .param1(Float.NaN)
                .param2(Float.NaN)
                .param3(Float.NaN)
                .param4(Float.NaN)
                .param5(Float.NaN)
                .param6(Float.NaN)
                .param7(Float.NaN)
                .build();
mavlinkConnection.send2(1,1, rtlMessage );

What's wrong with this command?
