### ISSUE TITLE
How to change the coptermode for example loiter, brake, auto,rtl etc?

### ISSUE THREAD

**Issue by ImranGA** [dronefleet/mavlink#43]

**Comment by ImranGA** [comment]
Brake and Land coptermode not working,componentarm_disarm not working, clearmission not working

**Comment by ImranGA** [comment]
Brake and Land coptermode not working,componentarm_disarm not working, clearmission not working

**Comment by benbarkay** [comment]
This library just does the part of sending/receiving messages to the
dialect's specifications, what is done with the messages depends on the
firmware of the autopilot (which differs between versions too).

As for modes, you should look into the custom mode field of your autopilot,
each autopilot has their own go at this iirc.
