### ISSUE TITLE
[General guidance] Documentation for using the generator gradle plugin

### ISSUE THREAD

**Issue by Drkstr** [dronefleet/mavlink#53]
Hi,
      I have the MavLink project(`io.dronefleet.mavlink:mavlink:1.1.8`) imported into my Android project but I am not seeing classes for parsing or generating messages. Guessing I need to generate these using the generator gradle plugin. 

Do you have any documentation or examples on how I should use the plugin?

**Comment by benbarkay** [comment]
There aren't such classes. The XML processing happens at build-time, and it generates annotated classes from it such as `Heartbeat`, which you can then use to build message objects that can be serialized or deserialized via `ReflectionPayloadSerializer` or `ReflectionPayloadDeserializer`.

If you want a custom message, then you have 2 options at the moment:
1. You could clone the repository, edit the XML files in `/definition-xml`, and then run the `generateDialect` gradle task; or
2. You could create your own `MavlinkDialect` implementation, depending on existing dialects (such as `CommonDialect`, for instance), and adding your own annotated message classes.

If you want to go for option 2, you can take a look at [UavionixDialect.java](https://github.com/dronefleet/mavlink/blob/master/src/main/java-gen/io/dronefleet/mavlink/uavionix/UavionixDialect.java) which depends on `CommonDialect` and adds some of its own messages.

**Comment by Drkstr** [comment]
Thanks for your reply, 

So I just do a gradle build to generate the common message parsing classes?
