### ISSUE TITLE
Overly complicated coding practices leading to difficult usage

### ISSUE THREAD

**Issue by Enlade** [dronefleet/mavlink#6]
I think that a lot of things were done in this effort that are just overly complicated. Such things force limitations on the user, but more importantly since you have scarce documentation it makes it difficult to figure out how to properly use this code.

For example, the code relies far to much on annotations.  Why on earth would you annotate FLAGS, MODES, and other constants.  Moreover, why would you annotate the message ID's?  How is anyone supposed to create a case statement that manages all the messages coming from the UAV (many hundreds)?  Your sample suggests that we are to create hundreds of "if" statements? This is a bottleneck routine, so that would be silly. So, the user is forced to create his/her own set of constants for each message ID so that he/she can use them in the message handler case statement. Not a big deal, but that is something that they need to manage separately from your code, when it really should be a part of your code.  Still, even with such a set of ID constants, the user still has to get the ID of the received message by writing a long line of code to extract the ID from the annotations when you could have just tossed the ID into the MavLinkMessage class.  I know it is in the actual payload, but the user can't get to that until they determine what type of message it is.  The ID of the received message should be available to the MavLinkMessage object. Well, it is, but the user has to know how to use annotations to get it.  Again, I know this is not a huge deal, but why?!??  Are you trying to win the International Obfuscated code contest or something?  I mean, take a look at the example code:

connection.send(new MavlinkMessage<>(
        255, // our system id
        0, // our component id (0 if we're a ground control system)
        Heartbeat.builder()
                .type(MavType.MAV_TYPE_GCS)
                .autopilot(MavAutopilot.MAV_AUTOPILOT_INVALID)
                .systemStatus(MavState.MAV_STATE_UNINIT)
                .mavlinkVersion(3)
                .build()));

Why do you do it this way?  Are you trying to just avoid having to set the attributes in multiple lines of code or something?  Is it just because you want to be able to fit everything on one line?  I can tell you that most of your users will be expecting to set each attribute up on multiple calls.  When they run into this they are surely going to be a bit puzzled, so all you are really doing is making the use of your code difficult.  To add insult to injury, this sample code seems to be missing a parameter after the component ID.  Can you guess what it is?  Yes, it is the message ID, which is annotated, so now I have to go outside of your code and put that in directly myself or I could extract the annotation with a long line of confusing code.  I mean, it isn't a big deal, but it just seems like you are being deliberately confusing.  Its almost like you want to show people that you know all these tricks, but it isn't the way you should write such code.  I know that some of what you are doing is so that you can manage all the messages in a more organized way on the back end, but that doesn't mean you want to force your users to do the same on the front end, it is just confusing.  I also understand that some of your usage of annotations is simply to prevent the user from trying to use a value that is outside the scope of such attributes, but I think maybe you went overboard with the annotations is all.  I don't claim to be the best JAVA programmer, but odds are a lot of people that are trying to use your code will be less proficient than I am, so why fill your code with complicated trickery?  I am really just venting a bit here, so I do apologies, but I thought maybe it will help you to satisfy your users if I say something.

Can you write me some skeleton code that manages say 200 messages coming from the UAV?  For instance, most users would expect something like this:

MavlinkConnection connection = MavlinkConnection.create(in, out); // InputStream, OutputStream
MavlinkMessage message;
while ((message = connection.next()) != null) {
    switch (message.Id) {   //<=== No such IVar so cannot do this
        case MAVLINK_MSG_ID_HEARTBEAT : {  //MAVLINK_MSG_ID_HEARTBEAT = 0
            //handle heartbeat
            Heartbeat tempmsg = (Heartbeat) message.getPayload();
            ...
            ...
        } break;
        case MAVLINK_MSG_ID_SYS_STATUS : {  //MAVLINK_MSG_ID_SYS_STATUS = 1
            //handle system status
        } break;
...
...
...
        case MAVLINK_MSG_ID_ATTITUDE_CONTROL : {  //MAVLINK_MSG_ID_ATTITUDE_CONTROL = 200
            //handle attitude control
        } break;
        default: {
            System.out.println("MSG Error : unknown MsgId (" + myMsgID + ")");
        }
    }
}

There is no list of constants for each message ID, and there is no IVar for message.Id, so the above can't be done.  I suppose I could do something to grab the annotation out of the message payload, maybe this?

int myMsgID = ((MavlinkMessageInfo) msg.getPayload().getClass().getAnnotation(MavlinkMessageInfo.class)).id();

Not sure if that is right, but looks OK.  Any better ways to get the Id?  If not then at least put that type of information in your documentation so people have some clue how to get the message IDs.

In any case, how do you suggest this message handler be done?  By putting a bunch of "if" statements with "instanceof" comparisons?  Which do you think will be more efficient code, a 200+ "if" statements or a single case statement?

Anyway, that's my troubles, likely I'm just confused, I hope that I am and you can correct my confusion.  I hope I'm not coming across angry or mean.  I am just trying to express my confusion with the way the code seems to have been written.  It really is likely just that there is so little documentation that it is leading me astray.  Sorry about that.

**Comment by Enlade** [comment]
Ok, so,  your example doesn't include the message ID as the third parameter.  So, to fix that would you want me to do something like this (adding the getAnnotation):

DANPacs.mavlinkRecieve.connection.send(new MavlinkMessage<>(
DANPacs.mySysId, // our system id
DANPacs.myComponentId, // our component id (0 if we're a ground control system)
Heartbeat.class.getAnnotation(MavlinkMessageInfo.class).id(),
Heartbeat.builder()
.type(MavType.MAV_TYPE_GCS)
.autopilot(MavAutopilot.MAV_AUTOPILOT_INVALID)
.systemStatus(MavState.MAV_STATE_UNINIT)
.mavlinkVersion(3)
.build())
);

**Comment by benbarkay** [comment]
Hi @Enlade, thanks for the feedback. I can understand three points that seem to pain you:
1. It is hard for you to get message IDs, and other mavlink-specific information from the generated code;
2. It's unmanageable for you to filter through incoming messages with `if` statements;
3. You find it hard to build the message objects using the builder pattern.

As for 1, `MavlinkMessage` does not accept a message ID in the constructor, it knows what the message ID is from the annotations of the Payload class (`Heartbeat` in this class)

As for 2, the idea is that you will use some form of sub-pub mechanism, like RxJava2 for example:

```java
Observable<Object> observable = PublishSubject.create();

// this is where you publish an incoming message
while ((message = connection.next()) != null) {
    observable.onNext(message.getPayload()); 
}
observable.onComplete();


// this is where you subscribe to messages
observable.ofType(Heartbeat.class)
    .subscribe((heartbeat) -> {
        // do whatever you want with the heartbeat here.
    });
```

And about 3, it's generally a good idea to use builders when there are potentially a lot of parameters, because it allows you to omit some parameters and it also associates the values with a name, so it's more readable. Perhaps it is a good idea to also generate a static constructor for these :)

Please let me know if I've missed something, hopefully this helps put you on track.

**Comment by Enlade** [comment]
Thank you for the fast response.  I think you answered my questions.  I'll have to look into using Observable object as I don't know if that avoids the efficiency issue or not.  Either way, it seems more elegant, so I'll do it that way.  Thank you again for your help.  The code is definitely very useful to me, and it benefits me much more then any small personal issues I might have with it.  So, thank you again.

**Comment by benbarkay** [comment]
Efficiency at the scale that you are mentioning shouldn't be a problem at all. Generally speaking, that switch statement is likely the most efficient thing compared to chained if/else or even an O(1) pub/sub if it will translate to a jump table by the JVM. But next to the IO operations that trigger these, your gains in performance would be about as significant as the loss of weight by removing an eyelash from a big bucket of cement.

**Comment by Enlade** [comment]
Hey, do you have a forum where I can post periodic questions and such?  I think I am starting to go into questions and I am not sure this is the place for them.  Like I was wondering how I could create a MavMode from a set of MavModeFlags.  Like I might want to pass an 89 to the SetMode message, which is perfectly fine to do, but since SetMode only takes MavMode as the base mode I can only send modes that are predefined within MavMode.  So, really I should not be restricted to just the fixed MavMode presets when I am passing the base mode (which should just be 8 significant bits).  Still, I'm not sure that this is the place for this conversation, but, if there is no way to pass an 89 (or whatever) then maybe base mode should not be of type MavMode.  If you think it is ok to just post here then I'm cool with that, but I don't want to confusing things if I am doing that.

**Comment by benbarkay** [comment]
There isn't one yet, but asking them here has the benefit of documenting what's missing, so for now it may be a good idea to do so.

You can create an `EnumValue` from any mavlink enum, you can, for instance, call:
```java
EnumValue.create(MavModeFlag.MAV_MODE_FLAG_SAFETY_ARMED, MavModeFlag.MAV_MODE_FLAG_GUIDED_ENABLED)
```
And that will create an `EnumValue` with both of these flags enabled.

The builders already allow you to specify varargs of enums for any `EnumValue` setter:
```java
SetMode.builder()
                /// ...
                .baseMode(MavModeFlag.MAV_MODE_FLAG_SAFETY_ARMED, MavModeFlag.MAV_MODE_FLAG_GUIDED_ENABLED)
                /// ...
```

**Comment by Enlade** [comment]
Yes, I posted that just before I stopped for the day and this morning I just noticed that base mode is of type EnumFlagSet<MavModeFlag> and not MavMode.  My bad.  Thank you for the quick response and the extra information though as it is helpful.

**Comment by Enlade** [comment]
Ahhhhhh, but SetMode only takes a MavMode.  Shouldn't that take a EnumFlagSet<MavModeFlag> instead?  The UAV is capable of accepting more modes than defined within MavMode, but all the possible modes would be covered if it was EnumFlagSet<MavModeFlag> instead.  right?

**Comment by Enlade** [comment]
I mean, Heartbeat treats baseMode as a EnumFlagSet<MavModeFlag> (which was part of my misunderstanding yesterday), but then shouldn't SetMode also treat baseMode as a EnumFlagSet<MavModeFlag> instead of as a MavMode?

**Comment by Enlade** [comment]
Oh, nevermind, I have some older version of your code.  It has baseMode as a MavMode, but I see in the current code it is a EnumFlagSet.  Let me update the entire code because that is causing a lot of problems.  sorry.

**Comment by benbarkay** [comment]
In the current version (1.0.9) all enum values are of type `EnumValue`, precisely because of the problem you are experiencing :)

**Comment by Enlade** [comment]
Hey, I see that baseMode for setmode was changed to EnumValue, but it is still of MavMode instead of MavModeFlag.

private final EnumValue<MavMode> baseMode;

If I want to perform a setMode with 89, how would I do that?

MAV_MODE_FLAG_MANUAL_INPUT_ENABLED (64), MAV_MODE_FLAG_STABILIZE_ENABLED (16), MAV_MODE_FLAG_GUIDED_ENABLED (8), MAV_MODE_FLAG_CUSTOM_MODE_ENABLED (1)

**Comment by Enlade** [comment]
Hey, I see that baseMode for setmode was changed to EnumValue, but it is still of MavMode instead of MavModeFlag.

private final EnumValue<MavMode> baseMode;

If I want to perform a setMode with 89, how would I do that?

MAV_MODE_FLAG_MANUAL_INPUT_ENABLED (64), MAV_MODE_FLAG_STABILIZE_ENABLED (16), MAV_MODE_FLAG_GUIDED_ENABLED (8), MAV_MODE_FLAG_CUSTOM_MODE_ENABLED (1)

**Comment by Enlade** [comment]
Hey, I see that baseMode for setmode was changed to EnumValue, but it is still of MavMode instead of MavModeFlag.

private final EnumValue<MavMode> baseMode;

If I want to perform a setMode with 89, how would I do that?

MAV_MODE_FLAG_MANUAL_INPUT_ENABLED (64), MAV_MODE_FLAG_STABILIZE_ENABLED (16), MAV_MODE_FLAG_GUIDED_ENABLED (8), MAV_MODE_FLAG_CUSTOM_MODE_ENABLED (1)

**Comment by Enlade** [comment]
Hey, I see that baseMode for setmode was changed to EnumValue, but it is still of MavMode instead of MavModeFlag.

private final EnumValue<MavMode> baseMode;

If I want to perform a setMode with 89, how would I do that?

MAV_MODE_FLAG_MANUAL_INPUT_ENABLED (64), MAV_MODE_FLAG_STABILIZE_ENABLED (16), MAV_MODE_FLAG_GUIDED_ENABLED (8), MAV_MODE_FLAG_CUSTOM_MODE_ENABLED (1)

**Comment by Enlade** [comment]
Opps...it cuts out stuff between greater than/less than symbols....here it is again.

`private final EnumValue<MavMode> baseMode;
`

**Comment by benbarkay** [comment]
```java
SetMode.builder()
                .baseMode(MavModeFlag.MAV_MODE_FLAG_MANUAL_INPUT_ENABLED, MAV_MODE_FLAG_STABILIZE_ENABLED, MavModeFlag.MAV_MODE_FLAG_GUIDED_ENABLED, MAV_MODE_FLAG_CUSTOM_MODE_ENABLED)
               .build()
```

**Comment by Enlade** [comment]
Ok, even though Heartbeat specifies the base mode enum as MavModeFlag's and SetMode specifies it as MavMode's, I can just cast everything to an simple EnumValue and use that wherever I need to?

**Comment by Enlade** [comment]
Is there a way to tell that the connection is actually connected to a MAVLink device?  In my code I loop through the multiple COM ports listening for a heartbeat message, if I don't hear one within some timeout it will move to the next COM port.  However, in your code it seems to stay in the MavlinkMessage.next method indefinitely, because it will just wait for a message even if it is not connected to a MAVLink device (I think).  So, what do I need to do to confirm that the device I connect to on some arbitrary COM port is actually a MAVLink enabled device so that I can move on to the next COM port if it is not?

**Comment by Enlade** [comment]
I am also running into an issue inside the MavlinkConnection.next code where it is checking to see if the massage is a heartbeat and updating the dialect.  It locks up there probably because the autopilot is null for some reason (though it doesn't give me any crash information, it just never returns from the call).  The deserializer returns the following empty heartbeat payload (toString):
 
Heartbeat{type=null, autopilot=null, baseMode=null, customMode=0, systemStatus=null, mavlinkVersion=0}

Since my code is also waiting for a heartbeat message I grab a number of messages prior to the heartbeat, so that "next" method gets called multiple times before it reaches the heartbeat code and locks up because autopilot is null.  I don't process any of the other messages as this is just setting up the system and I only start processing after I get a connection that has that first heartbeat.  So, it seems like the messages are coming through and passing the CRC checks and all that.  The code that it locks up on for me is:

`if (dialects.containsKey(heartbeat.autopilot().entry())) { … `

I believe this is because the autopilot is null, because I don't expect it to be null.  What am I doing wrong here?

**Comment by Enlade** [comment]
Yea, I put a toString in to print out all of the messages (payloads) returned from the deserializer, and they all print 0's and nulls for everything (Heartbeat, Attitude, etc).  Also, I do see the data in the rawBytes for each of these message (from the packet itself), and the toString (for the deserialized payload) does print all the proper field names for each message type, but all of the data is 0's or nulls.  Strange.

**Comment by Enlade** [comment]
It seems like it is not finding any of the MavlinkFieldInfo annotation in ReflectionPayloadDeserializer.  I tossed this code in just before where it deserializes those fields within the ReflectionPayloadDeserializer.

```
Stream<Method> myms = Arrays.stream(builder.getClass().getMethods()).filter(m -> m.isAnnotationPresent(MavlinkFieldInfo.class));

myms.forEach(mym-> {
        System.out.println(mym.toString());
});
```

And when I run that all of the messages show myms to be empty.  So, for some reason it is not finding the MavlinkFieldInfo's?

Is there some minimum requirement for JAVA?  I am using jdk/jre 1.8.0_66, and I am using the 32bit version of that at the moment.  Might that be the problem?

I have also copied your code into my project in a single directory structure under "io/dronefleet/mavlink/…".  I had to copy files from different folders into that single subfolder of my project. Everything seems to compile ok, but maybe I grabbed the wrong files when I combined everything into the one directory?  I think there were multiple versions of files in your project, so just want to make sure that wasn't the cause.  I mean, your code looks fine.

How about making annotations available at run time?  Does there need to be something like:

`@Retention(RetentionPolicy.RUNTIME)`

added somewhere in the code?

**Comment by Enlade** [comment]
I notice there are changes to annotation implementation in JAVA 8.

[http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html](url)


Says something about "method annotations being copied to synthetic bridge"?  Is it possible that that is what my problem is?

**Comment by benbarkay** [comment]
@Enlade this should not have anything to do with it. Have you tried adding a maven dependency for `1.0.9`?

**Comment by Enlade** [comment]
I can't use maven (at least not easily).  My development environment is offline and under management restrictions, so it is just difficult to deal with maven.

What version of JAVA are you using?  I think the issue might be that I am using 1.8 32bit (JAVA 8).  How does this code look to you for dumping all of the annotations?  It gives me all the methods, but no annotations.  I tried a number of different ways, but maybe I'm just doing it wrong.

```
Stream<Method> myms = Arrays.stream(Heartbeat.class.getMethods());
myms.forEach(mym-> {
	System.out.println("-- " + mym.toString());

	Annotation[] mya = mym.getClass().getAnnotations();
	for (Annotation a : mya) {
		System.out.println("      " + a.toString());		
	}
});
```

I'll install JAVA 7 and see if that helps; though, I think I am using libraries in my code that require 8+.  Still, I can run some tests with JAVA 7.

**Comment by Enlade** [comment]
Yea, I tried mym.getAnnotations() as well.  I see where you have done all of the stuff required by that oracle link I posted about JAVA 8 changes.  And I don't see any reason it wouldn't work.  So, it is likely something about how the project is setup as  you are saying.  I'll mess with that today and see if I can work it out.  Thanks.

**Comment by Enlade** [comment]
Here is a bit of strangeness.  If I remove the Comparator from the MavlinkFieldInfo.java, my little test code sees all of the other annotations and prints them out correctly.  Obviously this will break your ReflectionPayload...java codes, but it seems like that comparator is messing up the annotations that follow.

```
package io.dronefleet.mavlink.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Comparator;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface MavlinkFieldInfo {	
/*
	Comparator<MavlinkFieldInfo> WIRE_COMPARATOR = (a, b) -> {
        if (a.extension() && !b.extension()) {
            return 1;
        }
        if (!a.extension() && b.extension()) {
            return -1;
        }

        if (!a.extension() && a.unitSize() != b.unitSize()) {
            return b.unitSize() - a.unitSize();
        }

        return a.position() - b.position();
    };
*/
	
    int position();
    int unitSize();
    boolean signed() default false;
    int arraySize() default 0;    
    Class<?> enumType() default void.class;    
    boolean extension() default false;    
    String description() default "No description provided";
}

```

**Comment by Enlade** [comment]
So, maybe this is not an annotation issue I am running into at all, but rather something to do with the comparator?  Any ideas?  Can I just remove the sorts?

Just to note I'm using eclipse alone, and I have to do that because my development environment is restricted and offline.  I can do testing on other systems, but ultimately I need to get this working offline under eclipse.

**Comment by Enlade** [comment]
Also, there is still an issue where connection Next does not time out when it does not receive a heartbeat after some amount of time.  In my instance, I am cycling through the different COM ports to determine which port is connected to a MAVLink capable device.  It does this by waiting for some time for a heartbeat message to occur, but timing out when it does not occur and moving on to the next COM port.  Do you have any suggestions on how I might do this with your current code?  I can add a timeout to your code without much trouble, but maybe there are reasons for not having such timeouts that I am not thinking of (and again, I would prefer not to change your code if I can avoid it).

**Comment by Enlade** [comment]
I should say that since it is a subsystem the connection Next should timeout if it does not receive any message within some timeframe.  My code will timeout if it does not see a heartbeat and it will then move on to the next COM port.  Actually, it might be useful to just give the caller a mechanism to exit gracefully.  That way you could handle multiple use cases.  For instance, some users of your code might want to never time out.  They know the device is supposed to be connected to some COM port (say COM4), and they just want to wait until the connection is made (maybe the user just needs to turn on the UAV or some such).  Or in my case, I want to timeout so that I can move through the different possible COM ports automatically searching for the UAV.  This is because I don't want to user to have to choose a COM port, but the software will chose for them (like all the ground control software does for PX4 and APM).  So, maybe instead of adding a specific timeout you could just have some call that lets the user gracefully exit from the call to connection Next.  The first case would just never call it, and in my case I would call it after whatever amount of time I want to wait between COM ports.  Such would accommodate both use cases and others as well.

**Comment by Enlade** [comment]
Ok, so what I did was to change the comparator code in MavlinkFieldInfo to be this and it works fine.  So, I don't have to change any of your other code to get it to work, but just this one file. Do you see any problems in making this change in the way that I did ('new', '@Override', and such)?

```
package io.dronefleet.mavlink.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Comparator;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface MavlinkFieldInfo {	
	
	Comparator<MavlinkFieldInfo> WIRE_COMPARATOR = new Comparator<MavlinkFieldInfo>() {
		@Override
		public int compare(MavlinkFieldInfo a, MavlinkFieldInfo b) {
		    if (a.extension() && !b.extension()) {
		        return 1;
		    }
		    if (!a.extension() && b.extension()) {
		        return -1;
		    }
		
		    if (!a.extension() && a.unitSize() != b.unitSize()) {
		        return b.unitSize() - a.unitSize();
		    }
		    
		    return a.position() - b.position();
		};
	};
	
    int position();
    int unitSize();
    boolean signed() default false;
    int arraySize() default 0;    
    Class<?> enumType() default void.class;    
    boolean extension() default false;    
    String description() default "No description provided";
}

```

**Comment by Enlade** [comment]
Maybe I should break these issues into multiple threads in case people are looking for some specific answers?

1.  Managing the different enum variations of baseMode - Heartbeat returns baseMode as a <MavModeFlag>, but setmode wants it as <MavMode>, but that isn't a problem so long as you create the <MavMode> properly before passing it on to setMode.
2.  MavlinkFieldInfo annotations not working using Eclipse directly - turns out it is actually the Comparator that is not working for some reason, but have workaround.
3.  Connection.next() not timing out - some use cases will want this behavior, but others may want it to timeout or to be capable of being forced to stop in some way.

I'll probably have other questions that we might get into.  I can just work through them in this thread or I can open up multiples which can close when each is resolved.  Let me know what is best for you so I don't muddle up your threads too much.  I think the only one that is still outstanding is that Connection.next() issue.  But I still would like to know what you think about the MavlinkFieldInfo stuff as it seemed strange to me even if I have a workaround.  Thanks.

**Comment by Enlade** [comment]
Let me add another question to that list.

4. In my code I have a hierarchical list box that I use to allow the user to see the current field values for each message the program receives (whether the program processes the message or not).  You can see this same type of structure in QGroundControl and in Mission Planner where they allow you to view the Mavlink messages as they come in (building the structure with each message or updating existing messages).  What I had done with my Mavlink 1 code is to add a method to each of the message source codes that would return the message ID (as a unique identifier) and each of the messages fieldnames and values.  This can be done as XML or just some array of fieldname/value's, etc (I think I created a class with the ID and an array of fieldnames/values).  So basically something like toString(), but that returned the message information in a way that is more usable to controls like the one I mention.   Might that be useful for you to add that method to each of your message source files?  The advantage is that I can call that method without having to cast the payload so that I don't have to uniquely process each message I receive to still be able to report that the message was received.  Just like toString allows me to print out all the message details without casting it to any specific message type.

Oh, and maybe one more:

5. I still like the idea of making the message ID of the payload available without having to caste it either (maybe at the MavlinkMessage/MavlinkMessage2 level).  And also making a set of static values available for each message type so that a given received message ID can be easily compared to the constants list to determine what message type it is (I'm still stuck on that big case statement where you use the ID to quickly jump to the message handler code).  This may also be useful in implementing the above issue (4) as in my code I use the message ID as a means to determine if a message already exists in the hierarchical list box (so that it can be updated instead of being added to the list as a new message type).  I suppose the ID can still be used without me having to know what it actually represents, so such does not require me to have this issue added as well.  This is not a big deal if this doesn't get implemented, just want to make note of it.

I have a lot of questions, hopefully I am helping you by asking them.  Otherwise I apologies for be a nuisance.  Thanks for the help either way.

**Comment by Enlade** [comment]
So, for issue 4 I added the following to each of the message source files....in this example it is the Attitude message.

```
public ArrayList<MAVLinkFieldPair> getMAVLinkFields() {	
	ArrayList<MAVLinkFieldPair> mlf = new ArrayList<MAVLinkFieldPair>();

	mlf.add(new MAVLinkFieldPair("MAVLINK_MSG_ID_ATTITUDE", String.valueOf(MAVLINK_MSG_ID_ATTITUDE)));
	mlf.add(new MAVLinkFieldPair("time_boot_ms", String.valueOf(time_boot_ms)));
	mlf.add(new MAVLinkFieldPair("roll", String.valueOf(roll)));
	mlf.add(new MAVLinkFieldPair("pitch", String.valueOf(pitch)));
	mlf.add(new MAVLinkFieldPair("yaw", String.valueOf(yaw)));
	mlf.add(new MAVLinkFieldPair("rollspeed", String.valueOf(rollspeed)));
	mlf.add(new MAVLinkFieldPair("pitchspeed", String.valueOf(pitchspeed)));
	mlf.add(new MAVLinkFieldPair("yawspeed", String.valueOf(yawspeed)));
	    
	return(mlf);	
}
```

This could probably be done in a better way.  In this instance, I just created an array where the first element of the array is the message name and its ID.  So, I'm mixing the message ID information (parent) with that message fieldnames and values.  It is fine for the simple purpose I wanted to use it for, but maybe this would be different for a more robust solution (maybe it should return XML or some such).  What I will do as a workaround for my current code is to simply write a parser for the return of toString (not the best solution though and just more work).  I could add the above (or something like it) to each of the messages, but then I would have to add them each time you updated the code (or I could modify your generator I supposed).  In any case, hopefully you can see what I mean, this would give me access to the fields without having me to have to cast the message or manage all the messages I am not utilizing directly.

**Comment by Enlade** [comment]
So, instead a quick fix for me would be to get the ID from the annotations and pass it and the message toString() to a function like this (which just parses the string and builds the ArraryList that I pass on to my actual MAVMessage hierarchical display:

```
	public void updateMAVLinkMessage(int pID, String pST) {
		ArrayList<MAVLinkFieldPair> mlf = new ArrayList<MAVLinkFieldPair>();

		int fPos1 = pST.indexOf('{');
		int fPos2 = pST.lastIndexOf('}');

		mlf.add(new MAVLinkFieldPair(pST.substring(0, fPos1), String.valueOf(pID)));
		
		String[] fields = pST.substring(fPos1+1, fPos2).split(",");
		for (int i=0; i<fields.length; i++) {
			fPos1 = fields[i].indexOf('=');		
			mlf.add(new MAVLinkFieldPair(fields[i].substring(0, fPos1).trim(), String.valueOf(fields[i].substring(fPos1+1).trim())));
		}

		updateMAVLinkMessage(mlf);
	}
```
 
However, the problem might be that there is a possibility that some of the toStrings will vary in the format it returns and that will mess up this code somewhat.  Still, it is a quick fix that will get me something, and any messages that tangle with me can be modified.  However, would be nice to have the fields already organized for me by each message, I think.

**Comment by Enlade** [comment]
Yea, I'd have to also parse through the Enum types as well, but it isn't hard to do that, but its still a bit cluegy, would be nice to have each of the messages return all of its fields in a nice way where I don't have to cast it (string, string) like.

Well, I look back at all the messages and believe I may have typed too much stuff.  Sorry about that.  I'm off for the day.  See ya.

**Comment by Enlade** [comment]
Ok, so I went ahead and adjusted the toString parser to split it out.  I don't bother with giving the enums a new level in the way I'm storing them as it wasn't needed for me, but probably would be better to make the storage more hierarchical as well instead of just an one dimensional array, so anything you might do should probably be more hierarchical.  I also don't know if there is another level below the enum that I'm missing where another block of braces could kick in, but I think this is fine for a starting point.

```
	public void updateMAVLinkMessage(int pID, String pST) {
		ArrayList<MAVLinkFieldPair> mlf = new ArrayList<MAVLinkFieldPair>();

		int fPos1 = pST.indexOf('{');
		int fPos2 = pST.lastIndexOf('}');

		mlf.add(new MAVLinkFieldPair(pST.substring(0, fPos1), String.valueOf(pID)));
		
		String[] fields = pST.substring(fPos1+1, fPos2).split(",(?![^\\{]*[\\}])");
		
		for (int i=0; i<fields.length; i++) {
			fPos1 = fields[i].indexOf('{');
			if (fPos1<0) {
				fPos2 = fields[i].indexOf('=');
				mlf.add(new MAVLinkFieldPair(fields[i].substring(0, fPos2).trim(), String.valueOf(fields[i].substring(fPos2+1).trim())));								
			} else {
				fPos2 = fields[i].indexOf('=');
				String tempST1 = fields[i].substring(0, fPos2).trim();
				String tempST2 = "[";

				fPos2 = fields[i].lastIndexOf('}');
				String[] enumf = fields[i].substring(fPos1+1, fPos2).split(",");
				for (int j=0; j<enumf.length; j++) {
					if (j>0) tempST2 = tempST2 + ", ";

					fPos2 = enumf[j].indexOf('=');
					tempST2 = tempST2 + String.valueOf(enumf[j].substring(fPos2+1).trim());
				}
				tempST2 = tempST2 + "]";
				mlf.add(new MAVLinkFieldPair(tempST1, tempST2));							
			}
		}

		updateMAVLinkMessage(mlf);
	}

```

**Comment by Enlade** [comment]
Ok, I think I pulled out all the outstanding issues from this thread, so you can close it if you like.  Thank you.
